jobs:
- job: linux
  displayName: Linux
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      python3.6:
        python.version: '3.6'
      python3.7:
        python.version: '3.7'

  variables:
    CONDA_PKGS_DIRS: $(Pipeline.Workspace)/.conda/pkgs

  steps:
  - task: Cache@2
    inputs:
      key: 'conda | "$(Agent.OS)" | "python$(python.version)"'
      path: $(CONDA_PKGS_DIRS)
      restoreKeys: |
        conda | "$(Agent.OS)"
    displayName: Cache Conda packages

  - bash: |
      set -ex
      echo "##vso[task.prependpath]$CONDA/bin"
      conda config --set always_yes yes
      conda config --prepend channels conda-forge
      conda update --yes --quiet --name base conda
      conda info --all
    displayName: Configure Conda

  - bash: |
      set -ex
      source activate base
      conda create --yes --quiet --name pyomicron python=${PYTHON_VERSION}
      conda env update --quiet --name pyomicron --file=environment.yml
      conda install --yes --quiet --name pyomicron pytest-azurepipelines
    displayName: Create conda environment

  - bash: |
      set -ex
      source activate pyomicron
      python -m pip install --editable .
    displayName: 'Install pyomicron'

  - bash: |
      set -ex
      source activate pyomicron
      python -m pytest --cov --pyargs omicron --junit-xml=junit-results.xml
      python -m coverage run -a $(which omicron-hdf5-merge) --help
      python -m coverage run -a $(which omicron-print) --help
      python -m coverage run -a $(which omicron-process) --help
      python -m coverage run -a $(which omicron-root-merge) --help
      python -m coverage run -a $(which omicron-status) --help
    displayName: 'Run automated tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'junit*.xml'
    condition: succeededOrFailed()
    displayName: 'Upload test results'

  - bash: |
      set -ex
      source activate pyomicron
      conda install --yes --quiet --name pyomicron codecov
      python -m codecov --flags $(uname) python${PYTHON_VERSION/./}
    displayName: 'Upload coverage to codecov.io'
